#!/bin/bash

if [[ -z "$1" || -z "$2" ]]; then
	echo -e " rand_cpu_inj [FILESIZE] [MEMSIZE] [PARAM]...\n"\
	"create a random image and execute with qemu"\
	"\n\n\t"\
	"Filesize N:\tN KB"\
	"\n\t"\
	"Memory size:\tSupporting prefixes B, KB, MB, TB, PB, and EB. Default is MB."\
	"\n\t"\
	"Parameters:\tadditional params provided to qemu"\
	"\n\n"\
	"\$RFILE: destination of random image"
	exit 0
fi

if [[ -z $RFILE ]]; then
	RFILE="./rand.img"
fi
dd if=/dev/urandom of=$RFILE conv=notrunc bs=1024 status=none count=$1
./src/mkbootsect $RFILE
mv $RFILE.bin $RFILE
./src/startqemu $2 $RFILE ${@:3}
