#!/bin/bash

if [ $# -lt 2 ]; then
	echo "Usage: [RAM SIZE] [DISK] [PARAM]..."
	exit 0
fi
KVM_SUPPORT=""

if [ -c /dev/kvm ]; then
	KVM_SUPPORT="-enable-kvm"
fi
qemu-system-$(uname -p) -m $1 $2 ${@:3} $KVM_SUPPORT 2> /dev/null
if [ $? -ne 0 ]; then
	echo "KVM found but it is busy. Falling back to TCG..."
	qemu-system-$(uname -p) -m $1 $2 ${@:3}
fi
